# Generated by Django 4.1.5 on 2023-04-17 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Beden')),
                ('slug', models.SlugField(blank=True, verbose_name='Slug Beden')),
            ],
        ),
        migrations.CreateModel(
            name='Beden2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Beden')),
                ('slug', models.SlugField(blank=True, verbose_name='Slug Beden')),
            ],
        ),
        migrations.CreateModel(
            name='BedenAyakkabi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiyat', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Fiyat')),
                ('stok', models.IntegerField(default=0, verbose_name='Stok Miktarı')),
                ('beden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appMy.beden', verbose_name='Beden Numarası')),
            ],
        ),
        migrations.CreateModel(
            name='BedenKiyafet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiyat', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Fiyat')),
                ('stok', models.IntegerField(default=0, verbose_name='Stok')),
                ('beden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appMy.beden2', verbose_name='Beden')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Kategori')),
                ('slug', models.SlugField(blank=True, verbose_name='Slug Kategori')),
            ],
        ),
        migrations.CreateModel(
            name='Renk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Renkler')),
                ('slug', models.SlugField(blank=True, verbose_name='Slug Renk')),
            ],
        ),
        migrations.CreateModel(
            name='Urunler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='urun', verbose_name='Resim')),
                ('title', models.CharField(max_length=50, verbose_name='Başlık')),
                ('text', models.TextField(max_length=600, verbose_name='Açıklama')),
                ('puan', models.FloatField(default=0, verbose_name='Puan')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMy.category', verbose_name='Kategori')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
        migrations.CreateModel(
            name='UrunStok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beden_ayakkabi', models.ManyToManyField(blank=True, to='appMy.bedenayakkabi', verbose_name='Ayakkabı beden ve stok')),
                ('beden_kiyafet', models.ManyToManyField(blank=True, to='appMy.bedenkiyafet', verbose_name='Kıyafet beden ve stok')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMy.urunler', verbose_name='Ürün')),
            ],
        ),
        migrations.CreateModel(
            name='UrunImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', models.ImageField(upload_to='urun', verbose_name='Resim')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMy.urunler', verbose_name='Ürün')),
            ],
        ),
        migrations.AddField(
            model_name='bedenkiyafet',
            name='renk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMy.renk', verbose_name='Renk'),
        ),
        migrations.AddField(
            model_name='bedenkiyafet',
            name='urun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMy.urunler', verbose_name='Ürün'),
        ),
        migrations.AddField(
            model_name='bedenayakkabi',
            name='renk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMy.renk', verbose_name='Renk'),
        ),
        migrations.AddField(
            model_name='bedenayakkabi',
            name='urun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMy.urunler', verbose_name='Ürün'),
        ),
    ]
