# Generated by Django 4.1.5 on 2023-04-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urunler',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug Title'),
        ),
    ]
