# Generated by Django 4.1.5 on 2023-04-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0003_shopbasket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopbasket',
            name='price_all',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Toplam Fiyat'),
        ),
    ]
