# Generated by Django 4.1.5 on 2023-04-19 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0006_bedenkiyafet_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bedenkiyafet',
            name='user',
        ),
    ]
