# Generated by Django 4.1.5 on 2023-04-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0007_remove_bedenkiyafet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedenayakkabi',
            name='fiyat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Fiyat'),
        ),
        migrations.AlterField(
            model_name='bedenkiyafet',
            name='fiyat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Fiyat'),
        ),
        migrations.AlterField(
            model_name='shopbasket',
            name='price_all',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Fiyat'),
        ),
    ]
