# Generated by Django 4.1.5 on 2023-04-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0011_alter_comment_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_now',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tarih-Saat'),
        ),
    ]
